#!/usr/bin/python3.6
import sys
sys.path.append('../Santorini')
from Admin.tournament_manager import TournamentManager

tournament_manager = TournamentManager()
tournament_manager.read_config_from()
out = tournament_manager.run_tournament()
print(json.dumps(out))
