#!/usr/bin/python3.6
import sys
import os
import json
sys.path.append('..')
from Santorini.Admin.tournament_manager import TournamentManager

tournament_manager = TournamentManager()
tournament_manager.read_config_from()
out = tournament_manager.run_tournament()
print(json.dumps(out))
