#!/usr/bin/env python3.6
import sys
sys.path.append('../Santorini')
from Admin.referee import Referee
from Observer.observer import Observer
from Tests.player_mocks.legit_player import LegitPlayer
import uuid

uuids_players = {
    uuid.uuid4() : LegitPlayer(),
    uuid.uuid4() : LegitPlayer()
}

referee = Referee(uuids_players)

referee.add_observer(Observer())

referee.run_game()
