#!/usr/bin/env python3.6

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "..")) 
import json
from Santorini.Common.player_interface import AbstractPlayer
from Santorini.Remote.remote_proxy_server import RemoteProxyServer
from Santorini.Lib.dyn_import import find_subclass_in_source
from multiprocessing import Process
import importlib
import importlib.util
import inspect
import time

WAIT_BETWEEN_PLAYERS = 1 # in seconds

config = json.loads(sys.stdin.read())

ip = config["ip"]
port = config["port"]

playerconfigs = config["players"]
player_components = []
for player_spec in playerconfigs:
    _, name, path = player_spec

    player_class = find_subclass_in_source(path, AbstractPlayer)
    if player_class:
        player = player_class()
        client_connection = RemoteProxyServer(ip, port, player, name)
        player_components.append(client_connection)

def start_rps(rps):
    """
    Starts a remote proxy server
    :param RemoteProxyServer rps: the server to start
    """
    rps.start()

player_procs = []

for rps in player_components:
    p = Process(target=start_rps, args=[rps])
    player_procs.append(p)
    p.start()
    time.sleep(WAIT_BETWEEN_PLAYERS)

for p in player_procs:
    p.join()
