#!/usr/bin/python3
import sys
import json

in_exprs = []

out_exprs = []

# raw input text as a string
in_str = sys.stdin.read()

# JSON decoder to decode JSON objects
decoder = json.JSONDecoder()

# strips whitespace from the input string because it can
# mass up the JSON decoder
in_str.lstrip()

# loop to get separate and store JSON objects
while in_str:
    expr, index = decoder.raw_decode(in_str)
    in_exprs.append(expr)
    in_str = in_str[index:].lstrip()

for i in range(len(in_exprs)):
    print(json.dumps([len(in_exprs) - i - 1, in_exprs[i]], separators=(",", ":")))
